---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletest-service-sm
  namespace: default
  labels:
    release: prometheus-operator
spec:
  endpoints:
  - port: metrics
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: scaletest-service
...
